### ISSUE TITLE
`ModuleNotFoundError: No module named 'cloudflare_exceptions'`

### ISSUE THREAD

**Issue by insilications** [moonbuggy/cfscrape-http-proxy#1]
It seems the latest version of cloudscrapper has deprecated cloudflare_exceptions.

`ModuleNotFoundError: No module named 'cloudflare_exceptions'`

https://github.com/VeNoMouS/cloudscraper/issues/154

Once I remove all usage of this module, the proxy works perfectly.

**Comment by moonbuggy** [comment]
Thanks for pointing this out, and apologies for the slow reply. The device I'm running this proxy on keeps destroying power supplies for some reason, so my local CFS proxy has been down and I've not noticed this problem myself yet.

It looks like VeNeMouS pushed changes to the module within a few days of me pushing my code that uses the module. Life's kinda funny like that. :) That's not a complaint against VeNeMouS, of course. Sometimes you just have to chuckle at the timing of the universe/entropy/chaos.

I've been away from the computer a lot lately for a variety of reasons, but I'll sort this out within the next week or two.

Thanks again.

**Comment by moonbuggy** [comment]
I apparently got distracted for nearly two whole years. :)

The dodgy module import has now been removed, amidst a general code cleanup.
